### ISSUE TITLE
Search params loader is incompatible with raw fumen code

### ISSUE THREAD

**Issue by frey-mz** [knewjade/tetris-fumen#13]
fumen codes with special characters do not load properly through direct link
example: v115@9gF8DeF8CeG8BeH8CeA8JeAgWEAa+VWC

the [fumen link](https://fumen.zui.jp/?v115@9gF8DeF8CeG8BeH8CeA8JeAgWEAa+VWC) is able to load the fumen from its url code but the [pc solver link](https://wirelyre.github.io/tetra-tools/pc-solver.html?fumen=v115@9gF8DeF8CeG8BeH8CeA8JeAgWEAa+VWC) is not

this is because special characters in the fumen code are raw and get parsed differently than intended

**Comment by knewjade** [comment]
@freyhoe It looks like an issue to send to https://github.com/wirelyre/tetra-tools, isn’t it? If it's correct, please close this.

**Comment by frey-mz** [comment]
sorry, misclicked project
