### ISSUE TITLE
field.fill can't draw floating pieces

### ISSUE THREAD

**Issue by eight04** [knewjade/tetris-fumen#2]
data: https://harddrop.com/fumen/?v115@vhAVLn
Code:
```js
const {decoder} = require("tetris-fumen");
const pages = decoder.decode("v115@vhAVLn");
console.log(pages[0].field.str());
pages[0].field.fill(pages[0].operation);
```
Result:
```
Error: Cannot fill piece on field
```
[REPL](https://runkit.com/embed/m4fe8vk9hmwj)

Is this intended? Quote from README:

> Fill piece even if not on the ground, and return the mino as the placed

If floating pieces are not allowed, how does it differ from `field.put`?

**Comment by knewjade** [comment]
@eight04 Sorry, it's bug. I fixed it in v1.1.1. thank you.
